# Please check here for all available settings: https://github.com/rubocop-hq/rubocop/blob/master/config/enabled.yml

require: rubocop-rspec

AllCops:
  Exclude:
    - 'db/migrate/**/*'
    - 'app/views/**/*'
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'config/**/*'
    - 'log/**/*'
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'

Gemspec/DeprecatedAttributeAssignment: # new in 1.30
  Enabled: true

Layout/LineEndStringConcatenationIndentation: # new in 1.18
  Enabled: true
Layout/SpaceBeforeBrackets: # new in 1.7
  Enabled: true
Layout/LineLength:
  Max: 100
  #  IgnoredPatterns: ['\A#'] # ignore long comments (ex. generated annotation comments)
  Exclude:
    - 'spec/**/*.rb'
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Layout/EmptyLinesAroundExceptionHandlingKeywords:
  Enabled: false
Layout/SpaceInsideParens:
  Enabled: true
Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'spec/**/*.rb'
Layout/LineContinuationLeadingSpace: # new in 1.31
  Enabled: true
Layout/LineContinuationSpacing: # new in 1.31
  Enabled: true


Lint/UnreachableLoop:
  Enabled: false
Lint/RaiseException:
  Enabled: false
Lint/StructNewOverride:
  Enabled: false
Lint/RescueException:
  Enabled: false
Lint/AmbiguousOperator:
  Enabled: false
Lint/Debugger:
  Enabled: true
Lint/ConstantOverwrittenInRescue: # new in 1.31
  Enabled: true
Lint/NonAtomicFileOperation: # new in 1.31
  Enabled: true
Lint/RefinementImportMethods: # new in 1.27
  Enabled: true
Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*.rb"


Metrics/AbcSize:
  Enabled: false
  Max: 100
  Exclude:
    - 'spec/**/*.rb'


Metrics/BlockLength:
  Max: 150
  Exclude:
    - 'config/routes.rb'
    - 'config/environments/*.rb'
    - 'lib/tasks/*.rake'
    - 'app/views/**/*.json.jbuilder'
    - 'spec/**/*.rb'

Metrics/ClassLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 20
  Enabled: false

Metrics/MethodLength:
  Max: 200
  Enabled: false

Metrics/ModuleLength:
  Max: 400
  Enabled: false


Metrics/ParameterLists:
  CountKeywordArgs: false
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false
  Max: 20

Naming/VariableNumber:
  CheckSymbols: false
Naming/AccessorMethodName:
  Exclude:
    - 'app/rpc/**/*.rb'
Security/CompoundHash: # new in 1.28
  Enabled: true
Style/ClassAndModuleChildren:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*.rb'
Style/Documentation:
  Enabled: false
Style/DoubleNegation:
  Enabled: false # converting objects to true/false is a known ruby idiom.
Style/Lambda:
  Enabled: false # double line -> operator is OK
Style/FrozenStringLiteralComment:
  EnforcedStyle: never
Style/MixinUsage:
  Exclude:
    - 'bin/*' # ignore auto generated bin stubs
Style/StringLiterals:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/TrailingCommaInArguments:
  Enabled: false # because it makes for less commit noise
Style/TrailingCommaInArrayLiteral:
  Enabled: false # because it makes for less commit noise
Style/TrailingCommaInHashLiteral:
  Enabled: false # because it makes for less commit noise
Style/WordArray:
  Enabled: false
Style/EmptyElse:
  Enabled: false
Style/HashEachMethods:
  Enabled: false
Style/HashTransformKeys:
  Enabled: false
Style/HashTransformValues:
  Enabled: false
Style/SlicingWithRange:
  Enabled: false
Style/EnvHome: # new in 1.29
  Enabled: true
Style/FetchEnvVar: # new in 1.28
  Enabled: true
Style/MapCompactWithConditionalBlock: # new in 1.30
  Enabled: true
Style/NestedFileDirname: # new in 1.26
  Enabled: true
Style/ObjectThen: # new in 1.28
  Enabled: true
Style/RedundantInitialize: # new in 1.27
  Enabled: true
Style/ExponentialNotation:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
  # mathematical symbols are easier to grasp than
  # text when comparing money values
Style/RegexpLiteral:
  Enabled: false
Style/NumericLiteralPrefix:
  Enabled: false 
Style/EmptyHeredoc:
  Enabled: false 


# RSpec related:
RSpec/Capybara/SpecificMatcher:
  Enabled: false
RSpec/Rails/HaveHttpStatus:
  Enabled: true
RSpec/AlignLeftLetBrace:
  Enabled: false
RSpec/AlignRightLetBrace:
  Enabled: false
RSpec/AnyInstance:
  Enabled: false
RSpec/AroundBlock:
  Enabled: true
RSpec/Be:
  Enabled: true # please don't disable this! it hurts my brain! use `.not_to be_nil`
RSpec/BeEql:
  Enabled: false
RSpec/BeforeAfterAll:
  Enabled: false
RSpec/ContextWording:
  Enabled: false
RSpec/DescribeClass:
  Enabled: false
RSpec/DescribeMethod:
  Enabled: false
RSpec/DescribeSymbol:
  Enabled: false
RSpec/DescribedClass:
  Enabled: false
RSpec/EmptyExampleGroup:
  Enabled: false
RSpec/EmptyLineAfterExampleGroup:
  Enabled: false
RSpec/EmptyLineAfterFinalLet:
  Enabled: false
RSpec/EmptyLineAfterHook:
  Enabled: false
RSpec/EmptyLineAfterSubject:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/ExampleWithoutDescription:
  Enabled: false
RSpec/ExampleWording:
  Enabled: false
RSpec/ExpectActual:
  Enabled: false
RSpec/ExpectChange:
  Enabled: false
RSpec/ExpectInHook:
  Enabled: false
RSpec/ExpectOutput:
  Enabled: false
RSpec/FilePath:
  Enabled: false
RSpec/Focus:
  Enabled: false
RSpec/HookArgument:
  Enabled: true
  EnforcedStyle: implicit
RSpec/HooksBeforeExamples:
  Enabled: false
RSpec/ImplicitExpect:
  Enabled: false
RSpec/ImplicitSubject:
  Enabled: false
RSpec/InstanceSpy:
  Enabled: false
RSpec/InstanceVariable:
  Enabled: true
RSpec/ItBehavesLike:
  Enabled: false
RSpec/IteratedExpectation:
  Enabled: false
RSpec/LeadingSubject:
  Enabled: false
RSpec/LetBeforeExamples:
  Enabled: false
RSpec/LetSetup:
  Enabled: false
RSpec/MessageChain:
  Enabled: false
RSpec/MessageExpectation:
  Enabled: false
RSpec/MessageSpies:
  Enabled: false
RSpec/MissingExampleGroupArgument:
  Enabled: true
RSpec/MultipleDescribes:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/MultipleSubjects:
  Enabled: true
RSpec/NamedSubject:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
RSpec/NotToNot:
  Enabled: false
RSpec/OverwritingSetup:
  Enabled: true
RSpec/Pending:
  Enabled: false
RSpec/PredicateMatcher:
  Enabled: true
RSpec/ReceiveNever:
  Enabled: false
RSpec/RepeatedExample:
  Enabled: false
RSpec/ReturnFromStub:
  Enabled: true
  EnforcedStyle: and_return
RSpec/ScatteredLet:
  Enabled: false
RSpec/ScatteredSetup:
  Enabled: false
RSpec/SharedContext:
  Enabled: true
RSpec/SharedExamples:
  Enabled: true
RSpec/SingleArgumentMessageChain:
  Enabled: false
RSpec/SubjectStub:
  Enabled: false
RSpec/SubjectDeclaration:
  Enabled: false
RSpec/UnspecifiedException:
  Enabled: true
RSpec/VerifiedDoubles:
  Enabled: false
RSpec/VoidExpect:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/FactoryBot/SyntaxMethods:
  Enabled: true
RSpec/ExcessiveDocstringSpacing: # new in 2.4
  Enabled: true
RSpec/IdenticalEqualityAssertion: # new in 2.4
  Enabled: true
RSpec/Rails/AvoidSetupHook: # new in 2.4
  Enabled: true
RSpec/BeEq: # new in 2.9.0
  Enabled: true
RSpec/BeNil: # new in 2.9.0
  Enabled: true
RSpec/ChangeByZero: # new in 2.11.0
  Enabled: true
RSpec/VerifiedDoubleReference: # new in 2.10.0
  Enabled: true




Lint/RequireRangeParentheses: # new in 1.7
  Enabled: true
Lint/AmbiguousAssignment: # new in 1.7
  Enabled: true
Lint/AmbiguousRange: # new in 1.19
  Enabled: true
Lint/DeprecatedConstants: # new in 1.8
  Enabled: true
Lint/DuplicateBranch: # new in 1.3
  Enabled: true
Lint/DuplicateRegexpCharacterClassElement: # new in 1.1
  Enabled: true
Lint/EmptyBlock: # new in 1.1
  Enabled: true
Lint/EmptyClass: # new in 1.3
  Enabled: true
Lint/EmptyInPattern: # new in 1.16
  Enabled: true
Lint/LambdaWithoutLiteralBlock: # new in 1.8
  Enabled: true
Lint/NoReturnInBeginEndBlocks: # new in 1.2
  Enabled: true
Lint/NumberedParameterAssignment: # new in 1.9
  Enabled: true
Lint/OrAssignmentToConstant: # new in 1.9
  Enabled: true
Lint/RedundantDirGlobSort: # new in 1.8
  Enabled: true
Lint/SymbolConversion: # new in 1.9
  Enabled: true
Lint/ToEnumArguments: # new in 1.1
  Enabled: true
Lint/TripleQuotes: # new in 1.9
  Enabled: true
Lint/UnexpectedBlockArity: # new in 1.5
  Enabled: true
Lint/UnmodifiedReduceAccumulator: # new in 1.1
  Enabled: true
Naming/InclusiveLanguage: # new in 1.18
  Enabled: true
Style/ArgumentsForwarding: # new in 1.1
  Enabled: true
Style/CollectionCompact: # new in 1.2
  Enabled: true
Style/DocumentDynamicEvalDefinition: # new in 1.1
  Enabled: true
Style/EndlessMethod: # new in 1.8
  Enabled: true
Style/HashConversion: # new in 1.10
  Enabled: true
Style/HashExcept: # new in 1.7
  Enabled: true
Style/IfWithBooleanLiteralBranches: # new in 1.9
  Enabled: true
Style/InPatternThen: # new in 1.16
  Enabled: true
Style/MultilineInPatternThen: # new in 1.16
  Enabled: true
Style/NegatedIfElseCondition: # new in 1.2
  Enabled: true
Style/NilLambda: # new in 1.3
  Enabled: true
Style/QuotedSymbols: # new in 1.16
  Enabled: true
Style/RedundantArgument: # new in 1.4
  Enabled: true
Style/RedundantSelfAssignmentBranch: # new in 1.19
  Enabled: true
Style/StringChars: # new in 1.12
  Enabled: true
Style/SwapValues: # new in 1.1
  Enabled: true
  
Gemspec/RequireMFA: # new in 1.23
  Enabled: true
Lint/AmbiguousOperatorPrecedence: # new in 1.21
  Enabled: true
Lint/IncompatibleIoSelectWithFiberScheduler: # new in 1.21
  Enabled: true
Lint/RequireRelativeSelfPath: # new in 1.22
  Enabled: true
Lint/UselessRuby2Keywords: # new in 1.23
  Enabled: true
Naming/BlockForwarding: # new in 1.24
  Enabled: true
Security/IoMethods: # new in 1.22
  Enabled: true
Style/FileRead: # new in 1.24
  Enabled: true
Style/FileWrite: # new in 1.24
  Enabled: true
Style/MapToHash: # new in 1.24
  Enabled: true
Style/NumberedParameters: # new in 1.22
  Enabled: true
Style/NumberedParametersLimit: # new in 1.22
  Enabled: true
Style/OpenStructUse: # new in 1.23
  Enabled: false
Style/SelectByRegexp: # new in 1.22
  Enabled: true
 
