---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/stocks":
    get:
      summary: list stocks
      responses:
        '200':
          description: successful
    post:
      summary: create stock
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                symbol:
                  type: string
                price:
                  type: string
                date:
                  type: string
              required:
              - name
              - model
  "/api/v1/stocks/{id}":
    parameters:
    - id: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show stock
      responses:
        '200':
          description: successful
    patch:
      summary: update stock
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                symbol:
                  type: string
                price:
                  type: string
                date:
                  type: string
              required:
              - name
              - model
    put:
      summary: update stock
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                symbol:
                  type: string
                price:
                  type: string
                date:
                  type: string
              required:
              - name
              - model
    delete:
      summary: delete stock
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
